<?php
$faucet_steps=2;
$adb=1;
$bwait=5;
$currency=6; // Change to the id for the currency being used
$apicode=''; // Enter the API Code you wish to pass
$privkey=''; // Enter the private API key you wish to pass
$verkey='9MZDv-plBmDkjQvuj0dcO2rQVpcLH7fN';
$hashkey='-8VuvJJe5jgXgfYVoXrHO-R5G5wtpg80';
$ref_percent=50;
$sitetitle=''; // Enter the site title
$domainname=''; // Enter your domain here
$setinterval=2;
$keywords='Ethereum, Free Ethereum, Ethereum Faucet, Ether Faucet, Bitcoin, Bitcoin Faucet';
$desc='Earn FREE Ethereum while you learn about cryptocurrency and play fun games!';
$solvemedia_active=1; 
$recap_active=1;
$recap_site=''; // ReCaptcha Site Key
$recap_secret=''; // ReCaptcha Secret Key
$anti_bot=3;
